SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, B.TOTAL_SALES
    FROM AUTHOR AS A
    JOIN (SELECT B.CATEGORY, B.AUTHOR_ID, SUM(B.PRICE * S.SALES) AS TOTAL_SALES
            FROM BOOK AS B
            JOIN BOOK_SALES AS S
            ON B.BOOK_ID = S.BOOK_ID
            WHERE S.SALES_DATE LIKE '2022-01%'
            GROUP BY B.AUTHOR_ID, B.CATEGORY
         ) AS B
    ON A.AUTHOR_ID = B.AUTHOR_ID
    ORDER BY AUTHOR_ID, CATEGORY DESC